### ISSUE TITLE
You must be authenticated to call this service (utils/kv@release/get)

### ISSUE THREAD

**Issue by andrembezerra** [balsimpson/alexa-radio#24]
I got this error today. Any clue what is going on? 

{"error":{"type":"RuntimeError","message":"You must be authenticated to call this service (utils/kv@release/get)","stack":"Error: You must be authenticated to call this service (utils/kv@release/get)\n    at IncomingMessage.<anonymous> (/opt/node_modules/lib/lib/request.js:116:21)\n    at IncomingMessage.emit (events.js:326:22)\n    at endReadableNT (_stream_readable.js:1241:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}}

**Comment by balsimpson** [comment]
Autocode has changed a lot since I made this. Let see if I can find the error.

**Comment by andrembezerra** [comment]
The service seems okay. I could use it earlier today. Did you fix anything?
